# -*- coding: utf-8 -*-
"""hospital readmission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VoT6KcFBqfrZXj88jwPKVI1D5ESQ27O
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df= pd.read_csv("/content/diabetic_data.csv")

df.shape

df.columns

df.isnull().sum()

df

"""DATA CLEANING"""

object_cols =[]
cols=list(df.columns)
for i in cols:
  if (df[i].dtype=='object'):
    object_cols.append(i)
object_cols

question_mark_cols=[]
for i in object_cols:
  if ((df[i]=='?').sum()>0):
    question_mark_cols.append(i)
    print(f"{i}       {(df[i]=='?').sum()}")

for i in question_mark_cols:
  print(f"{df[i].value_counts()}\n")

print(f"{df[df['diag_1']=='?'].value_counts()} \n")
print(f"{df[df['diag_2']=='?'].value_counts()} \n")
print(df[df['diag_3']=='?'].value_counts())

#since, the question marks in diag_1,diag_2 and diag_3 as compared to ~1,00,000 rows are almost negligible, we can drop the rows where ? comes in diag_1,diag_2 and diag_3
indices_to_drop=df[
    (df['diag_1']=='?') |
    (df['diag_2']=='?') |
    (df['diag_3']=='?')
].index
df=df.drop(indices_to_drop)

#now , we run this again:
question_mark_cols=[]
for i in object_cols:
  if ((df[i]=='?').sum()>0):
    question_mark_cols.append(i)
    print(f"{i}       {(df[i]=='?').sum()}")

#since, ~97000 weight values are ?, it is better to drop the column rather than replacing it
df=df.drop(columns=['weight'])

df=df.drop(columns=['payer_code'])

#replacing ? in payer_code, medical_speciality with unknown and race with the mode (as it is very less ~2000)
df['medical_specialty']= df['medical_specialty'].replace({"?":"Unknown"})
df['race']=df['race'].replace({"?":df[df['race']!='?']['race'].mode()[0]})

#running the code to find any ? left
object_cols =[]
cols=list(df.columns)
for i in cols:
  if (df[i].dtype=='object'):
    object_cols.append(i)
question_mark_cols=[]
for i in object_cols:
  if ((df[i]=='?').sum()>0):
    question_mark_cols.append(i)
    print(f"{i}       {(df[i]=='?').sum()}")
#hence, there are no ? left

"""EDA"""

for i in object_cols:
  print(f"{df[i].value_counts()}\n")

#we can also drop these 3 (unknown/invalid) rows fom gender:
gender_indices_to_drop= df[
    (df['gender']=='Unknown/Invalid')
].index
df=df.drop(gender_indices_to_drop)

#handling diag_1,diag_2 and diag_3
def diagnosis_handling(diag):
  if diag.startswith("V") or diag.startswith("E"):
    return 'Other'
  else:
    diag = float(diag)
    if (390 <= diag <= 459 or diag == 785):
      return "Circulatory"
    elif (460 <= diag <= 519 or diag == 786):
      return "Respiratory"
    elif (520 <= diag <= 579 or diag == 787):
      return "Digestive"
    elif (800 <= diag <= 999):
      return "Injury"
    elif (710 <= diag <= 739):
      return "Muscoloskeletal"
    elif (580 <= diag <= 629 or diag==788):
      return "Genitourinary"
    elif (140 <= diag <= 239):
      return "Neoplasms"
    elif int(diag)==250:
      return "Diabetes"
    else:
      return "Other"

df['diag_1']=df['diag_1'].apply(lambda x:diagnosis_handling(x))
df['diag_2']=df['diag_2'].apply(lambda x:diagnosis_handling(x))
df['diag_3']=df['diag_3'].apply(lambda x:diagnosis_handling(x))

df['previous_hospital_visits']=df['number_inpatient']+df['number_outpatient']+df['number_emergency']
df['total_procedures']=df['num_lab_procedures']+df['num_procedures']

def discharge_disposition_id_conversion(discharge_id):
  if(discharge_id in [1, 6, 8]):
    return "discharged home"
  elif(discharge_id in [2, 3, 4, 5, 22, 23, 24]):
    return "transferred"
  elif(discharge_id in [13, 14]):
    return "hospice"
  elif(discharge_id in [11, 19, 20, 21]):
    return "expired"
  if(discharge_id==7):
    return "left"
  else:
    return "unknown"

df['discharge_result']=df['discharge_disposition_id'].apply(lambda x:discharge_disposition_id_conversion(x))

df['discharge_result'].value_counts()

def admission_source_id_conversion(ad_id):
  if (ad_id in [1,2,3]):
    return 'referral'
  elif (ad_id in [4,5,6]):
    return "transfer"
  elif (ad_id == 7):
    return 'emergency'
  elif (ad_id == 11):
    return "routine"
  elif (ad_id == 8):
    return "court enforcement"
  else:
    return 'unknown'

df['admission_source'] = df['admission_source_id'].apply(lambda x:admission_source_id_conversion(x))

def admission_type_id_conversion(ad_id):
  if (ad_id in [1,2,7]):
    return 'emergency'
  elif (ad_id in [3,4]):
    return "routine"
  else:
    return 'unknown'

df['admission_type']=df['admission_type_id'].apply(lambda x:admission_type_id_conversion(x))

df=df.drop(columns=['discharge_disposition_id','number_outpatient','number_emergency','number_inpatient','num_lab_procedures','num_procedures'],axis=1)

df=df.drop(columns=['admission_type_id','admission_source_id','encounter_id', 'patient_nbr'],axis=1)

df['A1Cresult']=df['A1Cresult'].fillna("None")
df['max_glu_serum']=df['max_glu_serum'].fillna("None")

df['readmitted'] = df['readmitted'].replace({'>30': 1, '<30': 1, 'NO': 0})

df = df[df['discharge_result'] != 'expired']

counts = df['medical_specialty'].value_counts()
df['medical_specialty']=df['medical_specialty'].apply(lambda x:x if counts[x]>=100 and x!='Unknown' else 'other' )

df['medical_specialty']=df['medical_specialty'].replace({'Surgery-Thoracic':'Surgery-Cardiovascular/Thoracic','Hematology/Oncology':'Oncology',"Orthopedics-Reconstructive":"Orthopedics"})

#since, these columns have mostly NO
df=df.drop(columns=['examide','citoglipton','acetohexamide','troglitazone','metformin-pioglitazone','metformin-rosiglitazone','glimepiride-pioglitazone','glipizide-metformin'],axis=1)

"""FEATURE ENGINEERING

MODEL BUILDING
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler

cols_for_ohe = ['race','gender','admission_type', 'admission_source','medical_specialty','diag_1','diag_2','diag_3','discharge_result']

binary_cols=['change', 'diabetesMed']

cols_with_natural_order=['age','max_glu_serum', 'A1Cresult']

numeric_cols=['time_in_hospital', 'previous_hospital_visits','total_procedures']

anti_diabetic_meds = ['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol',
       'tolazamide','insulin',
       'glyburide-metformin']

age_order = ['[0-10)','[10-20)','[20-30)','[30-40)','[40-50)','[50-60)','[60-70)','[70-80)','[80-90)','[90-100)']
max_glu_order = ['None', 'Norm','>200','>300']
A1Cresult_order=['None','Norm', '>7','>8']
change_order=['No','Ch']
med_order=['No','Yes']
med_anti_diabetic_order = ['No', 'Down', 'Steady', 'Up']

col_transformer = ColumnTransformer([
    ('scaler',StandardScaler(),numeric_cols),
    ('ohe',OneHotEncoder(handle_unknown='ignore',sparse_output=False),cols_for_ohe),
    ('oe_age_max', OrdinalEncoder(categories=[age_order, max_glu_order, A1Cresult_order]),cols_with_natural_order),
    ('oe',OrdinalEncoder(categories=[change_order,med_order]),binary_cols),
    ('ome',OrdinalEncoder(categories=[med_anti_diabetic_order]*len(anti_diabetic_meds)),anti_diabetic_meds)
],remainder='drop')

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

X=df.drop(columns=['readmitted'])
y=df['readmitted']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

full_pipeline=Pipeline([
    ('preprocessor',col_transformer),
    ('rand_clf', RandomForestClassifier(
        n_estimators=700,
        max_depth=15,
        min_samples_leaf=10,
        class_weight= {0: 1, 1: 2},
        random_state=42,
        n_jobs=-1
    ))
])

full_pipeline.fit(X_train,y_train)

full_pipeline.score(X_train,y_train)

from sklearn.metrics import classification_report,confusion_matrix , ConfusionMatrixDisplay

y_pred = full_pipeline.predict(X_test)
print(classification_report(y_test,y_pred))

import joblib
joblib.dump(full_pipeline, 'Readmission_model.pkl')